name = "ayuda-venezuela"
main = "workers/api.ts"
compatibility_date = "2026-06-26"
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "ayuda-venezuela-db"
database_id = "00000000-0000-0000-0000-000000000000"
